services:
  client:
    image: solaris-client-dev
    ports:
      - "8080:8080"

  api:
    image: solaris-api-dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      CONNECTION_STRING: "mongodb://database:27017/solaris?replicaSet=rs0"
      CLIENT_URL: "http://localhost:8080"
      CORS_URLS: "http://localhost:8080"
      SMTP_ENABLED: false
      SERVER_URL: "http://localhost:3000"
      SESSION_SECRET: top_secret
      SESSION_SECURE_COOKIES: false
      FRONTEND_APP_SOCKETS_HOST: "localhost:3000"
      FRONTEND_APP_API_HOST: "http://localhost:3000"
    depends_on:
      - database
      
  jobs:
    image: solaris-jobs-dev
    environment:
      PORT: 3000
      CONNECTION_STRING: "mongodb://database:27017/solaris?replicaSet=rs0"
      CLIENT_URL: "http://localhost:8080"
      CORS_URLS: "http://localhost:8080"
      SMTP_ENABLED: false
      SERVER_URL: "http://localhost:3000"

    depends_on:
      - database

  database:
    image: mongo:7
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - "dbdata:/data/db"
    ports:
      - "27017:27017"

  mongo-init:
    image: mongo:7
    depends_on:
      - database
    restart: on-failure
    entrypoint: ["bash", "-c", "sleep 5 && mongosh --host database:27017 --eval \"try { rs.initiate({_id:'rs0',members:[{_id:0,host:'database:27017'}]}) } catch(e) { if (e.codeName !== 'AlreadyInitialized') throw e }\""]
volumes:
  dbdata:
